### ISSUE TITLE
Missing OpalIMUData Function in matlab examples

### ISSUE THREAD

**Issue by lorenzcsunikl** [tmcg0/bioslam#13]
Hi, 
I am trying your examples in matlab. I am not sure but it seems like your from 

_% construct a data file
imus=OpalIMUData(fullfile(testDataDir,'20170412-162455-Y2_TUG_5.h5'));

The function OpalIMUData is missing. Thanks in advance

**Comment by tmcg0** [comment]
Thanks for catching this! OpalIMUData.m was a custom MATLAB class I had on my path. Let me fix this example and I'll get back to you and close the issue. Thanks again.

**Comment by tmcg0** [comment]
Apologies for taking a while to get around to this @lorenzcsunikl. I've fixed the problem, and now the MATLAB implementation uses a new ImuData.m which I've include in matlab/utils. If you pull the latest version of dev it should be fixed.

**Comment by tmcg0** [comment]
As a bonus fix that I stumbled upon while fixing this pull request, the MATLAB examples now work with static IMU bias estimation. See [this comment](https://github.com/tmcg0/bioslam/issues/4#issuecomment-828896308) on the issue for more details!

I consider this issue closed. Let me know if you still have any problems!

**Comment by lorenzcsunikl** [comment]
Thanks for fixing this one!

**Comment by lorenzcsunikl** [comment]
However, I face the following Problem:

Error using imuPoseEstimationExample (line 33)
Invalid default value for property 'm_initRot3' in class 'imuPoseEstimator':
Unable to resolve the name gtsam.Rot3.Quaternion.

How did you include gtsam in matlab? The variables LD_LIBRARY_PATH  and LD_RUN_PATH exported. But Matlab cannot find gtsam.

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
shorlyn, @EastDong314, @yuntsewu, @chenqiyi, @flameOnYou, @WadeIntoCode, @kentinchen, @faustogut, @sipan-slivani, @bugMaker-237, @0xhelium, @mikelieber, @tc-ying, @paulorasilva, @benmagnifico, @6pro, @ALiwoto, @amitjindal, @fayazfinehomeint, @ITowl, @createinnovative, @prajaktaajog, @manhinhang, @expcat, @InDmitriy, @riodda, @DrunkenGod9, @peresmishnyk, @cpeng-pz, @ymbkxc, @yazeed, @zhaodylan, @naonak, @alykhan, @phuongnl, @mcapo1, @steffen-lorenz, @heian0224, @mkid1, @cat157, @emilyalvarado, @bahtusay, @BychkovRY, @Agash, @PengLoveHONG, @jugrajsingh, @dplew, @Tomrori, @mikhail-vazhenin, @van5150

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Butters3388214, @furechan, @zhuchuangang, @MichDe, @leoavenue, @uchitesplavat, @akhanalcs, @VijayHwang, @DonneJohn, @kdbcinco, @empirefam11, @dennisgrobe, @NotWabel, @stevekeol, @Re-Make-Re-Model, @alainaubert, @yeolgun, @Jackyhh, @tmsnvd, @joshuaonuoha, @iamantee, @giuin, @tlennon140, @yehia2amer, @alkber, @Johnsonzhug, @movodos, @penghp1991, @Piperidine, @CheeringRoger, @potatogim, @YC-Cheng, @yunuskiran, @KevinZK, @bluelight1324, @AlexTroshkin, @JoseRajah, @marcusbooyah, @Rp70, @HafizhS, @AronLiu1999, @chicago-joe, @DavidZhao2017, @mdnadeemm, @yourlocalgrimreaper, @PooyaAlamirpour, @kecci, @Gruschwick, @MohammadDabirsiaghi, @Monuinfoservice

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mkobbi, @yuyu82, @AminoAnalogy, @NotMoni, @blackcatpolice, @mwpro, @Eliot100, @raphaelparkermvps, @GaoFengxin, @osvaldoc, @MachineLemonade, @vrsystems, @natwijaya19, @okrylan, @appfromape, @OwenZ0711, @niu-niu, @gustavosmede, @theoriginalkien, @Bahchi, @arturaslt, @KDunc11, @DiabloDaN, @teddybearofdoom, @Averus-a, @JBrizz77, @liuqiba, @axiomaticcrab, @jdriscoll98, @robertheadley, @ICLXL, @nobiit, @spyrolabs, @ChaosExplorer, @Gregsai, @12gabriel3, @LavenHook, @Sharaddition, @chenyujiehome, @Sprinklemint, @code-groove-alien, @tamaroning, @bowwowden, @aiooo3838, @Papalloon, @Saw-mon-and-Natalie, @thewh1teagle, @nickpellant, @FredericChang, @MadhukarMoogala
